### PR TITLE
helping somebody

### PR DESCRIPTION
**Pull request by MikePendo**
- forcing it to work
- changes in tests

### CODE REVIEW

**Comment by nacho4d** [comment]
Thank you Mike. I merge this and want to try it!

**Comment by nacho4d** [comment]
@MikePendo 

Thank you for the fix. You made me remember that libraries need to have at least 1 class to have properties to work. :)

I checked the code and re-enabled the test that uses swift's URL (not NSURL).

https://github.com/nacho4d/spm-objc-category/actions/runs/4934310038/jobs/8819188176#step:4:18

I am still not able to use my new property `queryParams` from swift's URL type which is what I originally want to acchieve.
(I wonder why queryParams is not automatically bridged from NSURL to URL?)
```
Tests/URLUtilsTests/URLUtilsTestsSwift.swift:18:31: error: value of type 'URL' has no member 'queryParams'
        let queryParams = url.queryParams
                          ~~~ ^~~~~~~~~~~
error: fatalError
```

**Comment by MikePendo** [comment]
oooo I commented out by mistake `url.queryParams` and thought it was working, let me check once again

**Comment by MikePendo** [comment]
`let queryParams1 = (url as? NSURL)?.queryParams` that's also a kinda might be a valid work around.
@nacho4d I will try to look at it in the evening once again (need to go over my tasks)

**Pull request merged**
